-- Auto-generated by matugen via DMS theme worker
-- DO NOT EDIT MANUALLY

local M = {}

M.colors = {
	-- Core Material You colors
	primary = "#b8c4ff",
	on_primary = "#202c61",
	primary_container = "#374379",
	secondary = "#c2c5dd",
	on_secondary = "#2c2f42",
	background = "#121318",
	on_background = "#e3e1e9",
	surface = "#121318",
	on_surface = "#e3e1e9",
	surface_variant = "#45464f",
	outline = "#90909a",
	error = "#ffb4ab",

	-- dank16 ANSI palette (for border accents, etc.)
	color0 = "#121318",
	color1 = "#ff7297",
	color2 = "#7fff94",
	color3 = "#fff972",
	color4 = "#a1aef2",
	color5 = "#394376",
	color6 = "#b8c4ff",
	color7 = "#eff2ff",
}

-- Convenience aliases (Hyprland border colors expect 0xAARRGGBB)
-- Strip the leading # and prepend ff for full opacity
local function to_argb(hex)
	return "0xff" .. hex:sub(2)
end

M.argb = {}
for k, v in pairs(M.colors) do
	M.argb[k] = to_argb(v)
end

return M
